### ISSUE TITLE
Cakebox not streaming

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#12] opened 2015-03-18 19:21 UTC
Hi,
I have done mutiple installations so far in different servers , so far the cakebox dosen't seem to stream videos.

let me know if its is working on your end or there are any specific settings and I see plex already setup with your script , do we just need to tunnel it?

**Comment by toulousain79** [comment] 2015-03-18 22:47
Yes I know, me too... MKV is a good example.

I like your feedback, it is a precious help.
I am really frustrated because I can not work in MySB for now... No time, no computer. The week I am far of my home and my weekends is for my wife. I will be in this situation during 3 months (minimum), so please be patient.
Please continue to create new tickets. And when the time will come, I will work hard to satisfy you and all others users.
Maybe someone will help me...

**Comment by fravia1** [comment] 2015-03-19 08:00
Hey Sure  ,

No rush I am trying to see if I can fork-out and get some programmers on it.

Thanks for all your hard work to put this up .


Regards

**Comment by toulousain79** [comment] 2015-05-01 17:27
To confirmed by more users with version 2.1

**Comment by geroboame66** [comment] 2016-02-25 14:37
same probleme, i have vlc plugin and divx pro , but not work.
the only one good method is : copy link for file on cakebox and paste on vlc (open network file) ...
is it a probleme with version of vlc and/or divx ?
i use:
- vlc 2.2.2 x64 and  same version plugin for firefox.
- divx 10.2.0

**Comment by toulousain79** [comment] 2016-02-25 22:24
Yes I know, but I did not look at what the problem was. I hope I can handle it for version 3.3.
I do not know if the problem is the client (VLC, DivX or HTML5) or something else.
If you have ideas made me follow..

**Closed** 2016-08-27 20:14 UTC
